### PR TITLE
Fixed copyright year in footer

### PR DESCRIPTION
**Pull request by bmispelon**
I noticed that the year in the footer was out of date so I updated it.

I fixed the templates when I could so that it now automatically displays the current year.

However, I was not able to do that in the static HTML pages (error.html and maintenance.html) so on those pages I just incremented the year.

I also tried to use a dynamic year in the sphinx configuration file but I'm not sure if that's a valid solution.

Thanks!

### CODE REVIEW

**Comment by pydanny** [comment]
Could you merge in the latest and I'll accept this pull request?

**Comment by bmispelon** [comment]
@pydanny done :sparkles:

**Comment by pydanny** [comment]
Hmmm... tests are failing. I'll take a look at it today.

**Comment by pydanny** [comment]
The test failure is unaffiliated with this pull request so I'm brought this in anyway.

**Pull request merged**
