### PR TITLE
change repo watchers and its icon to stars fixes #295

### LINKED ISSUE #295: Change watchers to stars
e.g. "Repo Watchers"

### PR DESCRIPTION
**Pull request by santagada**
The color of the star icon is just a guess... I'm not a designer.

### CODE REVIEW

**Comment by audreyr** [comment]
@santagada really sorry about not seeing this sooner, it just slipped through the cracks. I remember when we talked about this. We're temporarily overwhelmed but will review asap.

**Comment by santagada** [comment]
I want to help more if there is anything I can do to make the process faster/easier for you just say it.

**Comment by pydanny** [comment]
Hi @santagada,

Right now were trying to get the site to pass all tests for the Django 1.8 upgrade.  There are a number of issues, and I've decided to halt the migration up until Django 1.8.1 comes out. Tomorrow morning I'll revert some code and make master run of Django 1.7.7. Then I'll update the docs to match and we'll take a look at your pull request.

**Comment by pydanny** [comment]
Actually, if you have experience migrating from Django 1.7 to 1.8 I'm would love your help.

**Comment by pydanny** [comment]
Apologies for the terribly slow response.

**Pull request merged**
